"""Add chat history tables

Revision ID: b6d0bd8fa816
Revises: add_handoff_and_state
Create Date: 2026-07-28 18:23:52.947098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b6d0bd8fa816'
down_revision = 'add_handoff_and_state'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.drop_table('contact_info_backup_jul2026')
    op.alter_column('contact_info', 'source',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'public_widget'::character varying"))
    op.alter_column('contact_info', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    # Constraint already dropped manually - commenting out to avoid error
    # op.drop_constraint(op.f('contact_info_conversation_id_key'), 'contact_info', type_='unique')
    op.create_index('ix_contact_info_assigned_to', 'contact_info', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_contact_info_conversation_id'), 'contact_info', ['conversation_id'], unique=True)
    op.create_index('ix_contact_info_created_at', 'contact_info', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_info_id'), 'contact_info', ['id'], unique=False)
    op.create_index('ix_contact_info_status', 'contact_info', ['status'], unique=False)
    op.create_index('ix_contact_info_updated_by', 'contact_info', ['updated_by'], unique=False)
    op.create_index('ix_conversation_history_conversation_id', 'conversation_history', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_history_created_at', 'conversation_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_history_id'), 'conversation_history', ['id'], unique=False)
    op.create_index('ix_conversation_history_role', 'conversation_history', ['role'], unique=False)
    op.create_index('ix_conversation_history_user_id', 'conversation_history', ['user_id'], unique=False)
    op.drop_constraint(op.f('conversation_state_conversation_id_key'), 'conversation_state', type_='unique')
    op.drop_index(op.f('ix_conversation_state_conversation_id'), table_name='conversation_state')
    op.create_index(op.f('ix_conversation_state_conversation_id'), 'conversation_state', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_state_id'), 'conversation_state', ['id'], unique=False)
    op.create_index('ix_conversations_created_at', 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index('ix_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    op.create_index('ix_documents_visibility', 'documents', ['visibility'], unique=False)
    op.create_index('ix_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index('ix_feedback_message_id', 'feedback', ['message_id'], unique=False)
    op.create_index('ix_feedback_rating', 'feedback', ['rating'], unique=False)
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index('ix_messages_role', 'messages', ['role'], unique=False)
    op.create_index('ix_project_conversation_created_at', 'project_conversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_conversation_id'), 'project_conversation', ['id'], unique=False)
    op.create_index('ix_project_conversation_request_id', 'project_conversation', ['request_id'], unique=False)
    op.create_index('ix_project_conversation_role', 'project_conversation', ['role'], unique=False)
    op.create_index('ix_project_conversation_user_id', 'project_conversation', ['user_id'], unique=False)
    op.alter_column('project_requests', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index('ix_project_requests_assigned_to', 'project_requests', ['assigned_to'], unique=False)
    op.create_index('ix_project_requests_created_at', 'project_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_requests_id'), 'project_requests', ['id'], unique=False)
    op.create_index('ix_project_requests_status', 'project_requests', ['status'], unique=False)
    op.create_index('ix_project_requests_user_id', 'project_requests', ['user_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_online',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    
    # Create new tables for chat history
    op.create_table(
        'chat_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=True),
        sa.Column('message_id', sa.Integer(), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_chat_messages_id', 'id'),
    )
    
    op.create_table(
        'chat_summaries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('key_points', sa.Text(), nullable=True),
        sa.Column('sentiment', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('conversation_id', name='uq_chat_summaries_conversation_id'),
        sa.Index('ix_chat_summaries_id', 'id'),
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_summaries')
    op.drop_table('chat_messages')
    
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_online',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_index('ix_project_requests_user_id', table_name='project_requests')
    op.drop_index('ix_project_requests_status', table_name='project_requests')
    op.drop_index(op.f('ix_project_requests_id'), table_name='project_requests')
    op.drop_index('ix_project_requests_created_at', table_name='project_requests')
    op.drop_index('ix_project_requests_assigned_to', table_name='project_requests')
    op.alter_column('project_requests', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_project_conversation_user_id', table_name='project_conversation')
    op.drop_index('ix_project_conversation_role', table_name='project_conversation')
    op.drop_index('ix_project_conversation_request_id', table_name='project_conversation')
    op.drop_index(op.f('ix_project_conversation_id'), table_name='project_conversation')
    op.drop_index('ix_project_conversation_created_at', table_name='project_conversation')
    op.drop_index('ix_messages_role', table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_index('ix_feedback_rating', table_name='feedback')
    op.drop_index('ix_feedback_message_id', table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index('ix_feedback_created_at', table_name='feedback')
    op.drop_index('ix_documents_visibility', table_name='documents')
    op.drop_index('ix_documents_uploaded_by', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index('ix_documents_created_at', table_name='documents')
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index('ix_conversations_created_at', table_name='conversations')
    op.drop_index(op.f('ix_conversation_state_id'), table_name='conversation_state')
    op.drop_index(op.f('ix_conversation_state_conversation_id'), table_name='conversation_state')
    op.create_index(op.f('ix_conversation_state_conversation_id'), 'conversation_state', ['conversation_id'], unique=False)
    op.create_unique_constraint(op.f('conversation_state_conversation_id_key'), 'conversation_state', ['conversation_id'])
    op.drop_index('ix_conversation_history_user_id', table_name='conversation_history')
    op.drop_index('ix_conversation_history_role', table_name='conversation_history')
    op.drop_index(op.f('ix_conversation_history_id'), table_name='conversation_history')
    op.drop_index('ix_conversation_history_created_at', table_name='conversation_history')
    op.drop_index('ix_conversation_history_conversation_id', table_name='conversation_history')
    op.drop_index('ix_contact_info_updated_by', table_name='contact_info')
    op.drop_index('ix_contact_info_status', table_name='contact_info')
    op.drop_index(op.f('ix_contact_info_id'), table_name='contact_info')
    op.drop_index('ix_contact_info_created_at', table_name='contact_info')
    op.drop_index(op.f('ix_contact_info_conversation_id'), table_name='contact_info')
    op.drop_index('ix_contact_info_assigned_to', table_name='contact_info')
    op.create_unique_constraint(op.f('contact_info_conversation_id_key'), 'contact_info', ['conversation_id'])
    op.alter_column('contact_info', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('contact_info', 'source',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'public_widget'::character varying"))
    op.create_table('contact_info_backup_jul2026',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('project_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('project_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('budget', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timeline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('preferred_contact_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('lead_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###